### ISSUE TITLE
add ROADMAP.md

### ISSUE THREAD

**Issue by jhserodio** [agrotis-io/vraw#16]
### What are you reporting?

* [ ] Bug that needs fixing
* [ ] Feature request
* [ ] Code refactor
* [x] Continuous Integration (CI) improvement
* [x] Changes in documentation (docs)
* [ ] Other

### What is the current behavior?
componente está sendo definido em versão para utilização, sendo que está em desenvolvimento.

### What is the expected behavior?
que seja definido que está atualmente no estagio de desenvolvimento de ambiente

### Which problem(s) will it solve?
- deixar claro que o produto está em desenvolvimento e qual o estagio de desenvolvimento dele com future features documentado no ROADMAP.md

- atualizar o versionamento para que a versão de desenvolvimento fique exposta na em realease.

**Comment by santospatrick** [comment]
we should list all the components we have today to put on it, i will do it tomorrow

**Comment by santospatrick** [comment]
**Components to Develop (Priority from up to bottom):** 
- [ ] Input
- [ ] AutoComplete
- [ ] DataTable
- [ ] Subtitle

**These does not have priority yet**
- [ ] Card
- [ ] CardCollapse
- [ ] ConfirmDialog
- [ ] EmptyList
- [ ] ItemFrame
- [ ] Link
- [ ] ListFrame
- [ ] Menu
- [ ] ModalDialog
- [ ] ModuleSwitch
- [ ] Progress
- [ ] QuickLinks
- [ ] SelectableList

**Comment by santospatrick** [comment]
**Features added/to add:**

- [x] [React](https://github.com/facebook/react/)
- [x] [Typescript](https://github.com/Microsoft/TypeScript)
- [x] [Storybook](https://github.com/storybooks/storybook)
- [x] [Jest](https://github.com/facebook/jest)
- [x] [Enzyme](https://github.com/airbnb/enzyme)
- [x] [Webpack](https://github.com/webpack/webpack)
- [x] [Prettier](https://github.com/prettier/prettier)
- [x] [Commitizen](https://github.com/commitizen)
- [x] [Semantic Release](https://github.com/semantic-release/semantic-release)
- [x] [Travis CI](https://travis-ci.org/agrotis-io/vraw)
- [x] [DangerJS](https://github.com/danger/danger-js)
- [ ] [BrowserStack](https://www.browserstack.com/)
